export default {
  AUTH_NAVIGATOR: 'AuthNavigator',
  APP_NAVIGATOR: 'AppNavigator',
  HOME_NAVIGATOR: 'HomeNavigator',
  CHAT_NAVIGATOR: 'ChatNavigator',
  SPLASHSCREEN: 'SplashScreen',
  LOGIN: 'Login',
  SINGUP: 'SingUp',
  HOME: 'Home',
  CONTINENT_PAGE: 'ContinentPage',
  COUNTRY_DETAIL: 'CountryDetail',
  FAVORITIES: 'Favorities',
  CHATROOMS: 'ChatRooms',
  CHATLIST: 'ChatList',
};
